### ISSUE TITLE
Analysis

### ISSUE THREAD

**Issue by koremus** [jcvdav/gfw_enso#5]
@jcvdav Did some writing and thinking about the paper. It generated these thoughts on the analysis:

1. Should we extend the analysis to MPAs? Foreign fishing is not a great proxy for illegal fishing, but adding MPAs may help convince readers these are costly decisions.

2. Thinking about costly decisions, do they fish for longer or further during El Nino or La Nina years? Can we get cumulative hours or distance on those years vs. neutral years?

**Comment by jcvdav** [comment]
@koremus I just got back into the office, we should have a call sometime this week.

1. Yes, I think we should. In fact, it might be worth exploring this as our main meassure of foreign fishing.
2. We can easily check on the cumulative hours. Distance might be trickier, depending on how we define it.

I'll read over your additions before we have the call to be sure we are on the same page.

**Comment by koremus** [comment]
@jcvdav I think we have a call scheduled for tomorrow! 10am your time, 1pm mine. Talk then!
